# Vectorization

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

: 

In [ ]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")


c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

# 벡터 연산을 통해 무려 300배 빠르게 수행
# 벡터화로 코드 속도를 크게 높일 수 있음
# 명시적 for 루프를 사용하지 말자!
# 벡터 연산은 simd 연산을 실행하는데 cpu보다, gpu에서 더 잘 작동한다. 이것이 바로 딥러닝에서 gpu를 사용하는 이유이다.

249805.63179205012
Vectorized version:0.9949207305908203ms
249805.63179205044
For loop:1079.5931816101074ms


: 

# Broadcasting

In [10]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [13]:
# reshape로 항상 계산 행렬 확인하기!
percentage = 100 * A /cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Python-Numpy Vectors

In [14]:
a = np.random.randn(5)

In [15]:
print(a)

[ 1.81208966  0.56684394 -0.8774304  -0.07281822  0.81444435]


In [16]:
print(a.shape)

(5,)


In [17]:
print(a.T)

[ 1.81208966  0.56684394 -0.8774304  -0.07281822  0.81444435]


In [23]:
# 이렇게 행렬 연산이 이뤄진다.
print(np.dot(a, a.T))

[[ 1.13463592  0.99562893 -0.24605738 -1.93520706  0.93922676]
 [ 0.99562893  0.87365202 -0.2159123  -1.69812016  0.82415982]
 [-0.24605738 -0.2159123   0.05336006  0.41966941 -0.20368091]
 [-1.93520706 -1.69812016  0.41966941  3.30064147 -1.60192201]
 [ 0.93922676  0.82415982 -0.20368091 -1.60192201  0.77747134]]


In [25]:
# 해결책 2중 배열로 만들어주자!
a = np.random.randn(5, 1)
print(a)

[[ 1.80976746]
 [-1.2477939 ]
 [-0.58589205]
 [-0.11284145]
 [-0.57136738]]


In [24]:
print(a.T)

[[ 1.0651929   0.93469354 -0.23099796 -1.81676676  0.88174335]]


In [26]:
print(np.dot(a, a.T))

[[ 3.27525826 -2.2582168  -1.06032837 -0.20421679 -1.03404209]
 [-2.2582168   1.55698962  0.73107253  0.14080288  0.71294873]
 [-1.06032837  0.73107253  0.3432695   0.06611291  0.33475961]
 [-0.20421679  0.14080288  0.06611291  0.01273319  0.06447393]
 [-1.03404209  0.71294873  0.33475961  0.06447393  0.32646068]]


In [1]:
# 따라서 딥러닝에서는 1차원 배열을 사용하지 않는다! rank = 1 사용 X

In [13]:
a = np.random.randn(4, 3)
b = np.random.randn(1, 3)
c = a * b
c.shape

(4, 3)

In [5]:
a=np.array([[2,1],[1,3]])
print(a*a)

[[4 1]
 [1 9]]


In [9]:
a = np.random.randn(4, 3)
b = np.random.randn(4, 1)

c = a.T + b.T
c

array([[-1.21079503,  0.44275064,  2.72334697,  0.79849848],
       [ 0.64208263, -1.0241167 ,  0.89099385,  1.04517413],
       [-0.55206954, -2.48449969,  0.16897241, -0.07320489]])

In [12]:
a = np.random.randn(4, 3)
b = np.random.randn(1, 3)
print(a)
print(b)
c = a ** 2 + b.T ** 2
c

[[-0.52127415 -0.32564161  0.25019859]
 [ 1.30744768  0.55184409  0.13324774]
 [ 0.88111106  0.75354162  0.27823261]]
[[ 1.54941791  0.09605016  0.24666319]
 [ 0.04123332  0.94055695  0.92487953]
 [-0.04554218 -0.93532162  0.82722667]]


array([[2.67242258, 0.10774265, 0.06467343],
       [1.71864508, 1.18917927, 0.8925815 ],
       [0.83719943, 1.42322711, 0.76171735]])